<a href="https://colab.research.google.com/github/sdw1621/python_numpy/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%84%98%ED%8C%8C%EC%9D%B4_CH01_02_%EB%84%98%ED%8C%8C%EC%9D%B4_%EB%AA%A8%EB%93%88%EC%9D%98_%ED%95%A8%EC%88%98_%ED%8A%B9%EC%A7%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**PDF 45, 예제 1 함수와 메소드 처리**

In [7]:
import numpy as np

In [8]:
a = np.zeros((5,5), dtype=np.int)

In [9]:
a.shape

(5, 5)

In [11]:
a != 0

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [12]:
(a != 0).any()

False

In [13]:
np.any(a != 0)

False

In [15]:
(a != 0).any

<function ndarray.any>

In [16]:
np.any

<function numpy.any>

In [17]:
np.ndarray.any is np.core.fromnumeric.any

False

In [18]:
help(np.ndarray.any)

Help on method_descriptor:

any(...)
    a.any(axis=None, out=None, keepdims=False)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [19]:
help(a.any)

Help on built-in function any:

any(...) method of numpy.ndarray instance
    a.any(axis=None, out=None, keepdims=False)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [20]:
np_ = set(dir(np))

In [21]:
nd_ = set(dir(np.ndarray))

In [22]:
npd_ = np_ & nd_

In [23]:
len(npd_)

48

In [24]:
count = 0
for i in list(npd_) :
  count += 1
  print(i, end=" ")
  if count % 5 == 0:
    print()

size imag max squeeze argsort 
choose shape real clip std 
all argpartition conj reshape nonzero 
min ravel copy round argmin 
partition var __doc__ put conjugate 
sort diagonal mean dtype take 
prod repeat swapaxes ndim __dir__ 
trace dot cumsum cumprod searchsorted 
compress argmax resize transpose ptp 
any nbytes sum 

In [28]:
a = dir(np)
a

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [27]:
np.ufunc

numpy.ufunc

In [29]:
import types

In [37]:
# 책 이상! error 난다. 

count = 0

for i in a:
  if i == "Tester":
    continue
  elif type(np.__dict__[i]) == types.FunctionType:
    count += 1
print(count)

KeyError: ignored

In [38]:
type(np.add)

numpy.ufunc

In [39]:
type(np.sort)

function

In [40]:
set(dir(np.add)) - set(dir(np.sort))

{'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types'}

In [41]:
a = np.array([1,2,3,4])

In [42]:
np.add(a,a)

array([2, 4, 6, 8])

In [43]:
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [44]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [45]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [46]:
c = a*b
c

array([ 60,  77,  96, 117])

In [47]:
d = a[:, np.newaxis]
d

array([[6],
       [7],
       [8],
       [9]])

In [48]:
d.shape

(4, 1)

In [49]:
e = b[np.newaxis, :]
e

array([[10, 11, 12, 13]])

In [50]:
e.shape

(1, 4)

In [51]:
f = d @ e
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [52]:
d.dot(e)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [53]:
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [54]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [55]:
np.sum(a2)

10

In [56]:
np.sum(a2, axis=0)

array([4, 6])

In [57]:
np.sum(a2, axis=1)

array([3, 7])

In [58]:
a3 = np.arange(1,9)
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
a3 = a3.reshape(2,2,2)
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
a3.shape

(2, 2, 2)

In [61]:
a3[0]

array([[1, 2],
       [3, 4]])

In [62]:
a3[1]

array([[5, 6],
       [7, 8]])

In [63]:
np.sum(a3)

36

In [64]:
np.sum(a3, axis=0)

array([[ 6,  8],
       [10, 12]])

In [65]:
np.sum(a3, axis=1)

array([[ 4,  6],
       [12, 14]])

In [66]:
np.sum(a3, axis=2)

array([[ 3,  7],
       [11, 15]])

In [67]:
a = np.array([4,5])

In [68]:
a.shape

(2,)

In [71]:
b = np.array([3,4,6])
b.shape

(3,)

In [72]:
try :
  a + b
except Exception as e:
  print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [73]:
a = np.append(a, [6])

In [74]:
a.shape

(3,)

In [75]:
a+b

array([ 7,  9, 12])

In [76]:
a2 = np.array([[1,2,3], [3,4,5]])

In [77]:
b2 = np.array([1,2])

In [78]:
try:
  a2 + b2
except Exception as e:
  print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


In [79]:
b2 = np.append(b2, [3])
b2.shape

(3,)

In [80]:
a2 + b2

array([[2, 4, 6],
       [4, 6, 8]])