<a href="https://colab.research.google.com/github/sdw1621/python_numpy/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%84%98%ED%8C%8C%EC%9D%B4_CH01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l = [ [1,2,3], [4,5,6]]

In [ ]:
type(l)

list

In [ ]:
print(l[0])

[1, 2, 3]


In [ ]:
print(l[1])

[4, 5, 6]


In [ ]:
for i, a in enumerate(l):
  for j, b in enumerate(a):
    print(l[i][j])

1
2
3
4
5
6


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [ ]:
np.ndarray.__name__

'ndarray'

In [ ]:
type(np.ndarray.var)

method_descriptor

In [ ]:
for i in dir(np.ndarray):
  if not i.startswith("_"):
    if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
      print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [ ]:
l = [1,2,3,4]

In [ ]:
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
t = (1,2,3,4)

In [ ]:
b = np.array(t)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a.data

In [ ]:
a.data.obj

array([1, 2, 3, 4])

In [ ]:
type(a.data.obj)

numpy.ndarray

In [ ]:
c = b

In [ ]:
c.base is b.base

True

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   2,   3,   4])

In [ ]:
b

array([100,   2,   3,   4])

In [ ]:
d = np.array(b)

In [ ]:
d[0] = 99

In [ ]:
d

array([99,  2,  3,  4])

In [ ]:
b

array([100,   2,   3,   4])

In [ ]:
e = np.array(l, dtype=np.float)

In [ ]:
e

array([1., 2., 3., 4.])

In [ ]:
e.dtype

dtype('float64')

In [ ]:
a2 = np.array( [[1,2,3], [4,5,6]] )

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.itemsize

8

In [ ]:
a2.size

6

In [ ]:
a2.strides

(24, 8)

###**PDF 26, 예제 3 넘파이 배열 원소 조회하기**

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
l

[1, 2, 3, 4]

In [ ]:
a[0]

1

In [ ]:
l[0]

1

In [ ]:
l2 = [[1,2,3],[4,5,6]]

In [ ]:
l2

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
try:
  l2[0,1]
except Exception as e:
  print(e)

list indices must be integers or slices, not tuple


In [ ]:
l2[0][1]

2

In [ ]:
a2[0,1]

2

In [ ]:
type(a2[0,1])

numpy.int64

In [ ]:
a2[0,1].item()

2

In [ ]:
type(a2[0,1].item())

int

In [ ]:
a2[0,1].real

2

In [ ]:
a2[0,1].imag

0

In [ ]:
na = np.array([[[1,2,3,],[4,5,6,]], [[1,2,3],[4,5,6]]])

In [ ]:
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
na.ndim

3

In [ ]:
na.shape

(2, 2, 3)

In [ ]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
na[0].shape

(2, 3)

In [ ]:
na.__array_interface__

{'data': (94483488672832, False),
 'descr': [('', '<i8')],
 'shape': (2, 2, 3),
 'strides': None,
 'typestr': '<i8',
 'version': 3}

In [ ]:
na.strides

(48, 24, 8)

In [ ]:
na.__array_interface__['data'][0]

94483488672832

In [ ]:
len(na.data.tobytes())

96

In [ ]:
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.data

In [ ]:
mem = memoryview(a)

In [ ]:
mem

In [ ]:
a.data[0]

1

In [ ]:
a.data.obj

array([1, 2, 3, 4])

In [ ]:
a.data.obj[0]

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [ ]:
b = np.array([999, 9999, 99999, 999999])

In [ ]:
b.data.hex()[:8]

'e7030000'

In [ ]:
hex(999)

'0x3e7'

In [ ]:
int('0x3e7', 16)

999

In [ ]:
divmod(999,16)

(62, 7)

In [ ]:
divmod(62,16)

(3, 14)

In [ ]:
divmod(3,16)

(0, 3)

In [ ]:
a.size

4

In [ ]:
for i in range(a.size):
  print(a[i])

1
2
3
4


In [ ]:
a.flat

In [ ]:
for i in a.flat:
  print(i)

1
2
3
4


In [ ]:
c = np.array([1,2,3,4], dtype=np.float_)

In [ ]:
c

array([1., 2., 3., 4.])

In [ ]:
x = np.frombuffer(c)

In [ ]:
x

array([1., 2., 3., 4.])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x[0]

1.0

In [ ]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [ ]:
x.base is c

True

In [ ]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

###**PDF 37, 1.4 다차원 배열의 두 클래스 비교**

In [ ]:
np.ndarray.__bases__

(object,)

In [ ]:
np.matrix.__bases__

(numpy.ndarray,)

In [ ]:
l1 = np.array([1,2,3,4,5,6,7,8])

In [ ]:
l1.shape

(8,)

In [ ]:
m1 = np.matrix([1,2,3,4,5,6,7,8])

In [ ]:
m1.shape

(1, 8)

In [ ]:
l2 = l1.reshape(2,4)

In [ ]:
l2.shape

(2, 4)

In [ ]:
m2 = m1.reshape(2,4)

In [ ]:
m2.shape

(2, 4)

In [ ]:
l3 = l2.reshape(2,2,2)

In [ ]:
try:
  m3 = m2.reshape(2,2,2)
except Exception as e:
  print(" 예외 ", e)

 예외  shape too large to be a matrix.


In [ ]:
m2_l = np.asmatrix(l1).reshape(2,4)

In [ ]:
m2_l

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
l2 * l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
try:
  m2 * m2
except Exception as e:
  print(e)

shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)


In [ ]:
np.multiply(m2, m2)

matrix([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

###**PDF 40, 예제 2 두 클래스 차이점 확인**

In [ ]:
nd_ = set(dir(np.ndarray))

In [ ]:
md_ = set(dir(np.matrix))

In [ ]:
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [ ]:
m4 = np.mat('1 2; 3 4')

In [ ]:
m4

matrix([[1, 2],
        [3, 4]])

In [ ]:
m4.A

array([[1, 2],
       [3, 4]])

In [ ]:
m4.getA()

array([[1, 2],
       [3, 4]])

In [ ]:
m4.H

matrix([[1, 3],
        [2, 4]])

In [ ]:
m4.T

matrix([[1, 3],
        [2, 4]])

In [ ]:
from numpy import linalg

In [ ]:
linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
m4.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
try:
  linalg.inv(m2)
except Exception as e:
  print(e)

Last 2 dimensions of the array must be square


In [ ]:
m2.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -1.92067893e-17],
        [ 4.25000000e-01, -1.25000000e-01]])