<a href="https://colab.research.google.com/github/sdw1621/python_numpy/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%84%98%ED%8C%8C%EC%9D%B4_CH01_03_%EB%B0%B0%EC%97%B4_%ED%95%A0%EB%8B%B9%EA%B3%BC_%EA%B2%80%EC%83%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.array([[1.2],[3,4]])
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1.2]), list([3, 4])], dtype=object)

In [5]:
b = a
b

array([list([1.2]), list([3, 4])], dtype=object)

In [6]:
a is b

True

In [7]:
a is b.base

False

In [8]:
b[0] = 999

In [9]:
a

array([999, list([3, 4])], dtype=object)

In [10]:
b

array([999, list([3, 4])], dtype=object)

In [11]:
f = np.array([4,5,6,7,8])

In [12]:
e = f.copy()

In [13]:
e.base is None

True

In [14]:
g = f[:]

In [15]:
g.base

array([4, 5, 6, 7, 8])

In [16]:
g.base is f

True

In [17]:
np.may_share_memory(g, f)

True

In [18]:
g[1] = 99999

In [19]:
g

array([    4, 99999,     6,     7,     8])

In [20]:
f

array([    4, 99999,     6,     7,     8])

In [21]:
h = f.view()

In [22]:
h

array([    4, 99999,     6,     7,     8])

In [23]:
h.base is f

True

In [24]:
np.may_share_memory(h, f)

True

In [30]:
a = np.array([1, 3, 5, 7])

In [31]:
b = np.array(a, copy=True)

In [29]:
b.base is None

True

In [32]:
c = np.array(a)

In [34]:
c.base is None

True

In [40]:
aa = np.array([1, 2, 3, 4, 5, 6, 7])

In [41]:
aa_c = np.sort(aa, axis=0)

In [42]:
aa_c

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
aa_c.base is None

True

In [44]:
aa[6] = 0

In [45]:
aa.sort()

In [46]:
aa

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
l = list(range(1, 10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
index = 1

In [57]:
l.__getitem__(index)

2

In [58]:
index = slice(1,3)

In [59]:
l.__getitem__(index)

[2, 3]

In [60]:
a = np.array([1,2,3,4,5,6,7])

In [61]:
index = 1

In [62]:
a.__getitem__(index)

2

In [63]:
index = slice(1,3)

In [64]:
a.__getitem__(index)

array([2, 3])

In [65]:
index = 1

In [66]:
a.__getitem__(index)

2

In [67]:
index = [1]

In [68]:
a.__getitem__(index)

array([2])

In [69]:
index = a < 4

In [70]:
index

array([ True,  True,  True, False, False, False, False])

In [71]:
a.__getitem__(index)

array([1, 2, 3])

In [72]:
index = a < 3

In [73]:
a.__setitem__(index, 9080)

In [74]:
a

array([9080, 9080,    3,    4,    5,    6,    7])